// CART
export enum CartActionsTypes {
  ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART",
  REMOVE_CART_ITEM = "REMOVE_CART_ITEM",
  PLUS_CART_ITEM = "PLUS_CART_ITEM",
  MINUS_CART_ITEM = "MINUS_CART_ITEM",
  CLEAR_CART = "CLEAR_CART",
}
// CART

// CATEGORY
export enum CategoryActionsTypes {
  SET_CATEGORY = "SET_CATEGORY",
  SELECT_CATEGORY = "SELECT_CATEGORY",
  SET_LOADED = "SET_LOADED",
}
// CATEGORY

// FILTERS
export enum FiltersActionsTypes {
  SET_SORT_BY = "SET_SORT_BY",
}
// FILTERS

// PRODUCTS
export enum ProductsActionsTypes {
  SET_PRODUCTS = "SET_PRODUCTS",
  SET_PRODUCT = "SET_PRODUCT",
  SET_LOADED = "SET_LOADED",
}
// PRODUCTS
